### PR TITLE
Have `change_dir_if_bundle` cd to Bundle Root instead of Resources dir

### PR DESCRIPTION
**Pull request by NHDaly**

### CODE REVIEW

**Comment by ranjanan** [comment]
LGTM

**Comment by NHDaly** [comment]
@ranjanan Ah, okay no wait, nvm I no longer think this PR is a good idea. I remember why I had things the way I had them before:

The app will change directories into the `Resources` directory. Therefore, anything you want to reference directly as a file, you put in `Resources`.

As for the _libraries_, the `Libraries` directory is added to the `LD_LIBRARY_PATH` during compilation ([here](https://github.com/NHDaly/ApplicationBuilder.jl/blob/4f1304d17fffe47495c58f3302e62777777e49cc/build_app.jl#L175)), and then added to the compiled binary's `rpath` ([here](https://github.com/NHDaly/ApplicationBuilder.jl/blob/4f1304d17fffe47495c58f3302e62777777e49cc/build_app.jl#L188)).

This way, the user code can simply refer to any local files directly, the same as they are relative to the repo directory, in the same way it would when running through regular julia. This is important so that the code works the same whether compiled or not. Here is one example from Paddle Battle:
https://github.com/NHDaly/PaddleBattleJL/blob/v1.0.3/main.jl#L409

Otherwise, those would have to be `"Resources/assets"` sometimes.

You originally asked this:
> So I was wondering if you wanted to set the default path to the Resources directory or straight to the bundle root, so now the user would have to specify paths to libraries by "Libraries/..." instead of "../Libraries/...

They _don't_ have to refer to the libraries via "../Libraries/...". In any `ccall`, they can simply write the library name (because of the `rpath`). If they want to refer to a library by name for some reason outside ccall, it is really a _resource_, not a library, and should go in `-R`. What do you think?


Is the problem coming for you for the windows version?

**Comment by ranjanan** [comment]
Yeah, so `rpath` is specific to Mac AFAIK. In windows, I'm bundling the following way: 
```
root:
- lib
- core
- res
```

and I change the library paths internally to `lib/` 

Would it be a massive problem to change to `Resources/assets/` for some files? Would be consistent on all three platforms.

**Comment by ranjanan** [comment]
Bump!

**Comment by NHDaly** [comment]
Hey, sorry, I've been very busy the last few weeks; my girlfriend graduated from grad-school this week, and now we're moving across the US to a new state! I should be more settled soon, hopefully. Thanks for the bump reminder.

> Yeah, so rpath is specific to Mac AFAIK

Yeah agreed that `rpath` is specific to Mac. So you're right that relying on that is probably not a good solution.

> and I change the library paths internally to `lib/`

Just wondering, what is the mechanism you're using for that right now?

> Would it be a massive problem to change to Resources/assets/ for some files? Would be consistent on all three platforms.

I agree that consistency on Windows/Linux/Mac is an important concern, we should find a solution that works the same for all of them!

My other concern is trying to maximize consistency between the code for "regular" julia operation and for a compiled application. That is, I want to make sure that the exact same code will work with Juno/Atom/command-line julia and then will also work when it's compiled.

And I also don't want to impose a directory structure on user's repos, which is why I opted for the `-R` and `-L` flags.

So however we organize the resultant compiled application, ideally we would `cd` to a location where the directory structure looks the same as the orginal repo from the code's perspective.

**Comment by NHDaly** [comment]
To be more clear, my main concern is to limit the number of `if IS_COMPILED` checks needed throughout the code, and so I think we should`cd` to a directory where the resources are available via the same path that they were in the original repo.

If there is a better solution for the `libs`, let's look into it!

**Comment by NHDaly** [comment]
Closing this stale PR

**Pull request closed without merging**
